// <auto-generated />
// Hand-rolled minimal snapshot — `dotnet ef` tooling expects this file when
// running `migrations add`. We use raw-SQL migrations (PostGIS / MV not
// supported by EF Core scaffolding), so this snapshot stays minimal and is
// regenerated whenever an `ef`-tooling migration is added in the future.

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace GeorgiaPlaces.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
public sealed partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Npgsql:PostgresExtension:pgcrypto", ",,")
            .HasAnnotation("Npgsql:PostgresExtension:postgis", ",,");
    }
}
